name: Generate assets

on:
  schedule: [{cron: "0 0 * * *"}]
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - main
    
jobs:
  generate-github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 5

    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_branch: assets/github-metrics
          filename: metrics.svg
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity
          base_indepth: yes

          plugin_lines: yes
          plugin_lines_delay: 10

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_introduction: yes
          plugin_introduction_title: no

          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
